### ISSUE TITLE
README does not provide details on project

### ISSUE THREAD

**Issue by katysill** [rbenzeev/reforestation-prioritization#2]
@rbenzeev 

It would be helpful if the README included additional information to provide some more context for your project.  Suggestions include who will be implementing the reforestation efforts, the extent and timeline of these efforts, how biodiversity levels and community support are defined, and the general importance of the reforestation project,

**Comment by rbenzeev** [comment]
@katysill 

Done! I added a background section as well as my research questions to my READ.me and I am now covering all your suggestions above in my description.
