### ISSUE TITLE
EAA-reforestation-prioritization-dataset not included on repo

### ISSUE THREAD

**Issue by katysill** [rbenzeev/reforestation-prioritization#4]
@ rbenzeev The helper script, EAA-week8-function.R references a data source "EAA-reforestation-prioritization-dataset.R" which does not appear to be included in the repo. If this dataset can be shared publicly, it would be helpful to include it in the data folder. If it can not be shared publicly, it would be helpful to provide some details about the contents of the data set so that another user could attempt to recreate the data and use the script.

**Comment by rbenzeev** [comment]
@katysill I added my dataset to the data folder and committed it so all data is now publicly available.
